NgStore2/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core_')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/home.png'))),
    path('vendors/', include('apps.vendor.urls', namespace='vendor_')),
    path('account/', include('apps.account.urls', namespace='account_')),
    path('cart/', include('apps.cart.urls', namespace='cart_')),
    path('chat/', include('apps.chats.urls', namespace='chat_')),
    path('order/', include('apps.order.urls', namespace='order_')),
    path('checkout/', include('apps.checkout.urls', namespace='checkout_')),
    path('message/', include('apps.communication.urls', namespace='message_')),
    path('', include('apps.product.urls', namespace='product_')),
    # path('', include('apps.order.urls', namespace='order_')),
    path('__debug__/', include(debug_toolbar.urls)),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/cart/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import url
from . import views


app_name="cart_"
urlpatterns = [
    path("cart_update_address/", views.cart_update_address, name="cart_update_address"),
    path('', views.cart_detail, name="cart_detail"),
    path('', views.shopping_cart, name="shopping_cart_"),
    path('success/', views.success, name="success_"),
    path("all/<str:rep>/", views.complete_payment, name="complete_payment2"),
]

apps/checkout/urls.py
from django.urls import include, path
from django.conf.urls import url

from . import views

app_name = "checkout_"

urlpatterns = [
    path("delivery-choices", views.deliverychoices, name="delivery_choice"),
    path("cart_update_delivery/", views.cart_update_delivery, name="cart_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("complete-my-payment", views.complete_payment, name="complete_payment2"),
    path("authenticating-user-details", views.user_details_authenticated, name="user_details_authenticated"),
]

apps/product/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .templatetags import searching


app_name="product_"
urlpatterns = [
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    path('search/', views.search, name="search_"),
    path('filter/', views.filter_page, name="filter_page"),
    path('search-for', views.search_single, name="search_single"),
    path('search-brand/', views.search_brand, name="search_brand"),
    path('check-category/', views.parent_child_check, name="parent_child_check"),
    path('<slug:category_slugz>/<slug:product_slugz>/', views.product_detail, name="product_detail_"),
    path('', views.product_detail2, name="product_detail2_"),
    path('<slug:category_slug>/', views.category_list, name="category_list_"),
    path('', views.vendor_category, name="vendor_category"),
    path('add-product/', views.add_product, name="add_product_"),
    path('add-category/', views.add_category, name="add_category_"),
    path('likes_add_and_remove/<int:id>', views.likes_add_and_remove, name="likes_add_and_remove"),
    path("likes/remove_from_likes/", views.remove_from_likes, name="remove_from_likes"),
    #path('product/', views.product_entry, name="product_"),
    path('', views.make_comment, name="make_comment"),
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/forms.py
from django import forms

class CheckoutForm(forms.ModelForm):
    first_name = forms.CharField(label='Firstname', min_length=2,  max_length=50, help_text='Required', error_messages={'required':'Sorry, firstname'})
    last_name = forms.CharField(label='Lastname', min_length=2,  max_length=50, help_text='Required', error_messages={'required':'Sorry, you will need an email'})
    email = forms.EmailField(label='Email', max_length=50, help_text='Required', error_messages={'required':'Sorry, you will need an email'})
    address = forms.CharField(label='Address', min_length=4,  max_length=50, error_messages={'required':'Sorry, you will need an email'})
    zipcode = forms.CharField(label='Zipcode', min_length=4,  max_length=50, help_text='Required', error_messages={'required':'Sorry, you will need an email'})
    place = forms.CharField(label='City', min_length=4,  max_length=50, help_text='Required', error_messages={'required':'Sorry, you will need an email'})
    phone = forms.CharField(label='Phone No', min_length=4,  max_length=50, help_text='Required', error_messages={'required':'Sorry, you will need an email'})
    stripe_token = forms.CharField(label='Stripe Token', min_length=4,  max_length=50, help_text='Required')

apps/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

from decimal  import Decimal

from .cart import Cart
from .forms import CheckoutForm
from apps.order.utilities import checkout, email_notify_vendor, email_notify_customer
from apps.vendor.models import Vendor
from apps.product.models import Product


from apps.checkout.models import DeliveryOptions
from apps.order.models import Address

#import stripe
@login_required
def complete_payment(request):
    print('')
def shopping_cart(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = CheckoutForm(request.POST)

    else:
        form = CheckoutForm()
    return render(request, 'cart/cart.html', {'form':form})#, 'stripe_pub_key':settings.STRIPE_PUB_KEY})

def success(request):
    return render(request, 'cart/index.html')

def cart_detail(request):
    cart = Cart(request)
    if request.POST:
        subAction = request.POST.get('subAction')
        productID = request.POST.get('productID')
        productQTY = 1
        if subAction == "delete":
            #item_quantity, item_total_cost, sub_total, total, delivery_price = cart.remove(product_id=productID)
            item_quantity, item_total_cost, sub_total, total, delivery_price = cart.remove(product_id=str(productID))
            response = JsonResponse(
                {'cart_length': cart.__len__(), "get_total_cost":cart.get_total_cost(),
                 'item_quantity': item_quantity,  'item_total_cost':item_total_cost,
                 'sub_total':sub_total, 'total':total, 'delivery_price':delivery_price})
            return response
        if subAction == 'add':
            product = get_object_or_404(Product, id=productID)
            product_exist = cart.add(product_id=productID, product=product, quantity=productQTY, update_quantity=False)
            response = JsonResponse(
                {'cart_length': cart.__len__(),'cart_length2': cart.__len__(), 'product_exist':product_exist})
            return response

        if subAction == 'update':
            product = get_object_or_404(Product, id=productID)
            item_quantity, item_total_cost, sub_total, total, delivery_price = cart.update(
                product_id=productID, product=product, quantity=productQTY, update_quantity=True)
            messages.success(request, 'The item was successfully updated in cart')
            response = JsonResponse(
                {'cart_length': cart.__len__(), "get_total_cost":cart.get_total_cost(),
                 'item_quantity': item_quantity, 'item_total_cost': item_total_cost,
                 'sub_total': sub_total, 'total': total, 'delivery_price': delivery_price})
            return response

        if subAction == 'subtract':
            product = get_object_or_404(Product, id=productID)
            item_quantity, item_total_cost, sub_total, total, delivery_price = cart.subtract(product_id=productID, quantity=productQTY, update_quantity=True)
            messages.success(request, 'The account was successfully subtracted from account')
            response = JsonResponse(
                {'cart_length': cart.__len__(), "get_total_cost":cart.get_total_cost(),
                 'item_quantity': item_quantity, 'item_total_cost': item_total_cost,
                 'sub_total': sub_total, 'total': total, 'delivery_price': delivery_price})
            return response


    session = request.session
    mydeliveryopt = {}
    mydeliveryadd = {}
    deliveryaddressess = {}
    if "purchase" in request.session:
        delivery_id = session["purchase"]['delivery_id']
        mydeliveryopt = DeliveryOptions.objects.get(id=delivery_id)
        deliveryoptions = DeliveryOptions.objects.filter(is_active=True).exclude(id=delivery_id)
    else:
        deliveryoptions = DeliveryOptions.objects.filter(is_active=True)
    if "address" in request.session:
        address_id = session["address"]['address_id']
        mydeliveryadd = Address.objects.get(id=address_id)
        if request.user.is_authenticated:
            deliveryaddressess = Address.objects.filter(customer=request.user).exclude(id=address_id)
    else:
        if request.user.is_authenticated:
            deliveryaddressess = Address.objects.filter(customer=request.user)

    print(deliveryoptions, "deliveryoptionsdeliveryoptions")
    return render(request, 'cart/cart.html', {
        'deliveryoptions':deliveryoptions, 'deliveryaddressess':deliveryaddressess,
        'mydeliveryopt':mydeliveryopt, 'mydeliveryadd':mydeliveryadd})


def cart_update_address(request):
    session = request.session
    if request.POST.get("action") == "post":
        address_id = str(request.POST.get("address_id"))
        Address.objects.filter(customer=request.user, default=True).update(default=False)
        Address.objects.filter(id=address_id, customer=request.user).update(default=True)
        address_type = Address.objects.get(id=address_id)
        if "address" not in session:
            session["address"] = {"address_id": address_id}
        else:
            session["address"]["address_id"] = address_id
            session.modified = True

    if request.POST.get("action") == "delete_address":
        address_id = str(request.POST.get("address_id"))
        Address.objects.filter(customer=request.user, id=address_id).delete()
        if "address" in session:
            if address_id == str(session["address"]["address_id"]):
                del session["address"]
                response = JsonResponse({'address_in_session':'true'})
                return response
    response = JsonResponse({'address_in_session': 'false'})
    return response

apps/cart/templates/cart/cart.html
{% extends 'core/base.html' %}
{% load static %}
{% block stylesheet %}{% static 'styles/cart/cart.css' %}{% endblock %}
{% comment %} {% block stylesheet2 %}{% static 'styles/order/deliver-address-details.css' %}{% endblock %} {% endcomment %}
{% comment %} {% block stylesheet2 %}{% static 'styles/breadcrumbs.css' %}{% endblock %} {% endcomment %}

{% block title %} Cart {% endblock %}
{% block content %}

<section id="main-container">
  <div class="main-box">
      {% if messages %}
      <div id="pop-notification" class="alert alert-success">
          <div class="alert alert-success">
              {% for message in messages %}
                {{message|safe}}.
              {% endfor %}
          </div>
      </div>
      {% endif %}

      <h1 class="main-head">Your Cart</h1>
      <div class="box">
          {% if cart %}
          <div class="inside-box">
              <div class="body-row">
                  {% for i in cart %}
                  <div data-index="{{ i.id }}" class="cart-item-block">
                      <div class="first-block">
                          <div class="block1">
                              <div class="innerblock1">
                                  {% for image in i.product.product_images.all %}
                                  {% if image.is_main %}
                                  <img class="" alt="cart image" src="{{ image.images.url }}" alt="{{ image.images.alt_text }}">
                                  {% endif %}
                                  {% endfor %}
                              </div>
                          </div>
                          <div class="block2">
                              <div class="innerblock">
                                  <div class="first-line">
                                      <a class="title" href="{% url 'product_:product_detail_' i.product.category.slug i.product.slug %}">{{ i.product.title }}</a>
                                      <div class="social">
                                        <button value="{{ i.id }}" data-index="{{ i.id }}" class="subtract-qty" type="button">
                                            <i style="color:#CCCDC6;" class="fa fa-minus"></i>
                                        </button>
                                        <span  data-index="{{ i.id }}" class="item-qty">{{ i.quantity }}</span>
                                        <button value="{{ i.id }}" data-index="{{ i.id }}" class="add-to-qty" type="button">
                                            <i class="fa fa-plus-circle"></i>
                                        </button>
                                      </div>
                                  </div>
                                  <div class="second-line">
                                      <div>
                                          <span class="price">N{{i.product.price}}</span>
                                          <div class="discount_price">
                                              <span class="price1">N{{i.product.discount_price}}</span>
                                              <span class="price2" style="color:var(--normalorange);font-size:14px;">saving </span>
                                              <span class="price3" style="color:var(--normalorange);font-size:14px;">N{{i.discount_amt}}</span>
                                          </div>
                                      </div>
                                      <button value="{{ i.id }}" data-index="{{ i.id }}" class="delete-item" type="button">
                                          <i class="fa fa-trash"></i> <span>Remove</span>
                                      </button>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="last-block">
                          <span style="position:absolute;top:20px;left:0;width:100%;height:1px;background-color:#BBBCB6;"></span>
                          <span style="position:absolute;top:95px;left:0;width:100%;height:1px;background-color:#BBBCB6;"></span>
                          <div class="block1">
                              <span style="width:100%;font-weight:600;margin-bottom:5px;text-align:center;">{{ i.product.title|slice:":20"  }}</span>
                              <div class="unit-price">
                                  <span>Unit Price</span><span data-index="{{ i.id }}" class="price_">N{% if i.product.discount_price %}{{ i.product.discount_price }} {% else %} {{ i.price }} {% endif %}</span>
                              </div>
                              <div class="discount">
                                  <span>Discount</span><span data-index="{{ i.id }}" class="discount_">{% if i.product.discount_price %} N{{ i.discount_percent }}% + {% else %} 0 {% endif %}</span>
                              </div>
                              <div class="unit-total">
                                  <span data-index="{{ i.id }}" class="qty_">Units Total (x{{ i.quantity }})</span><span data-index="{{ i.id }}" class="total_price_">N{{ i.total_price }}</span>
                              </div>
                              <div class="subtotal">
                                  <span>SUBTOTAL</span><span data-index="{{ i.id }}" class="subtotal_">N{{ i.total_price }}</span>
                              </div>
                          </div>
                      </div>
                  </div>
                  {% endfor %}
                {% include 'order/deliver-address-details.html' %}

              </div>
          </div>
          <div class="">
              <div class="">
                <a role="button" href="{% url 'checkout_:delivery_choice' %}" class="btn btn-success fw-bold" type="button">Checkout Securely</a>
                <button class="btn btn-light" type="button">Save for later</button>
              </div>
          </div>
          {% else %}
            <p>You dont have any product in your cart</p>
          {% endif %}
      </div>


  </div>
</section>
{% endblock %}

{% block scripts %}
    <script>
    $(document).ready(function(){
        $('.add-to-qty').on(
            {click: function(e){
                e.preventDefault();
                var prod_id=$(this).data('index');
                $.ajax({
                    type:"POST",
                    url:"{% url 'cart_:cart_detail' %}",
                    data: {
                        productID: $(this).data('index'),
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        mainAction: 'post',
                        subAction: 'update'
                    },
                    success: function(json){
                        $("a > .cart > .qty").text(json.cart_length);
                        $('.item-qty[data-index="'+ prod_id +'"]').text(json.item_quantity);
                        $('.unit-total > .qty_[data-index="'+ prod_id +'"]').text('Units Total ' + '(x' + json.item_quantity + ')')
                        $('.unit-total > .total_price_[data-index="'+ prod_id +'"]').text(json.item_total_cost);
                        $('.subtotal > .subtotal_[data-index="'+ prod_id +'"]').text('$' + json.item_total_cost);

                        $('.total-qty').text('$' + json.cart_length);
                        $('.total-cost').text('$' + json.sub_total);
                        $('#final-total').text('$' + json.get_total_cost);
                    },
                    error: function(xhr, errmsg, err){
                        console.log('completed with error');
                    }
                });

            }}
        )

        $('.subtract-qty').on(
            {click: function(e){
                e.preventDefault();
                var prod_id=$(this).data('index');
                $.ajax({
                    type:"POST",
                    url:"{% url 'cart_:cart_detail' %}",
                    data: {
                        productID: $(this).data('index'),
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        mainAction: 'post',
                        subAction: 'subtract'
                    },
                    success: function(json){
                        $("a > .cart > .qty").text(json.cart_length);
                        $('.item-qty[data-index="'+ prod_id +'"]').text(json.item_quantity);
                        $('.unit-total > .qty_[data-index="'+ prod_id +'"]').text('Units Total ' + '(x' + json.item_quantity + ')')
                        $('.unit-total > .total_price_[data-index="'+ prod_id +'"]').text(json.item_total_cost);
                        $('.subtotal > .subtotal_[data-index="'+ prod_id +'"]').text('$' + json.item_total_cost);

                        $('.total-qty').text('$' + json.cart_length);
                        $('.total-cost').text('$' + json.sub_total);
                        $('#final-total').text('$' + json.get_total_cost);

                    },
                    error: function(xhr, errmsg, err){
                        console.log('completed with error');
                    }
                });

            }}
        )

        $('.delete-item').on(
            {click: function(e){
                e.preventDefault();
                var prod_id=$(this).data('index');
                $.ajax({
                    type:"POST",
                    url:"{% url 'cart_:cart_detail' %}",
                    data: {
                        productID: $(this).data('index'),
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        mainAction: 'post',
                        subAction: 'delete'
                    },
                    success: function(json){
                        $("a > .cart > .qty").text(json.cart_length);
                        $('.total-qty').text('$' + json.cart_length);
                        $('.total-cost').text('$' + json.sub_total);
                        $('#final-total').text('$' + json.get_total_cost);
                        $('.cart-item-block[data-index="'+ prod_id +'"]').remove();

                        if (json.cart_length == 0){
                            $('.total').remove();
                            $('.box').html('<p>You dont have any product in your cart</p>');
                        };
                    },
                    error: function(xhr, errmsg, err){
                        console.log('completed with error');
                    }
                });

            }}
        )

    })
    </script>
{% endblock %}

apps/cart/templates/cart/success.html
{% extends 'core/base.html' %}

{% block title %} Success {% endblock %}
{% block content %}
    <h1 class="title">Thanks for the order</h1>
{% endblock %}