NgStore2/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core_')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/home.png'))),
    path('vendors/', include('apps.vendor.urls', namespace='vendor_')),
    path('account/', include('apps.account.urls', namespace='account_')),
    path('cart/', include('apps.cart.urls', namespace='cart_')),
    path('chat/', include('apps.chats.urls', namespace='chat_')),
    path('order/', include('apps.order.urls', namespace='order_')),
    path('checkout/', include('apps.checkout.urls', namespace='checkout_')),
    path('message/', include('apps.communication.urls', namespace='message_')),
    path('', include('apps.product.urls', namespace='product_')),
    # path('', include('apps.order.urls', namespace='order_')),
    path('__debug__/', include(debug_toolbar.urls)),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/communication/urls.py
from django.urls import path
from . import views

app_name="message_"
urlpatterns = [
    path("send-fleet-message", views.send_fleet_message, name="send_fleet_message"),
    path("<slug:user_unique_id>/<slug:logged_in_user_unique_id>", views.get_message, name="chat_platform2"),
    path("<slug:user_unique_id>/<slug:logged_in_user_unique_id>/", views.send_message, name="send_msg"),
    path("<slug:user_or_vendor_unique_id>", views.messages_history, name="messages_history"),
    path('', views.make_comment, name="make_comment"),
]

apps/communication/models.py
from django.db import models
from django.conf import settings

import datetime
import uuid

from apps.vendor.models import Vendor
from apps.account.models import UserBase


class Messages(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    #vendor = models.ForeignKey(Vendor, related_name='vendors_msg', on_delete=models.CASCADE)
    sender_id_unique = models.CharField(null=True, max_length=50)
    reciever_id_unique =  models.CharField(max_length=50)
    content =  models.CharField(max_length=255)
    is_seen = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'
        ordering=['-created_at']

    def __str__(self):
        return f'from {self.sender_id_unique} to {self.reciever_id_unique}'

    def get_date(self):
        time = datetime.datetime.now()
        if self.created_at.day == time.day:
            if self.created_at.hour == time.hour:
                return str(time.min - self.created_at.min) + " mins ago"
            else:
                return str(time.hour - self.created_at.hour) + " hours ago"
        else:
            if self.created_at.month == time.month:
                return str(time.day - self.created_at.day) + " days ago"
            else:
                if self.created_at.year == time.year:
                    return str(time.month - self.created_at.month) + " months ago"
                else:
                    return str() + str(self.created_at.day) + "/" +str(self.created_at.month) + "/" +str(self.created_at.year)
        return self.created_at

    #do this later
    def get_time(self):
        time = datetime.datetime.now()
        if self.created_at.hour == time.hour:
            return str(time.min - self.created_at.min) + " mins ago"
        else:
            if self.created_at.day == time.day:
                return str(time.hour - self.created_at.hour) + " hours ago"
            if self.created_at.month == time.month:
                return str(time.day - self.created_at.day) + " days ago"
            else:
                if self.created_at.year == time.year:
                    return str(time.month - self.created_at.month) + " months ago"
                else:
                    return str() + str(self.created_at.day) + "/" +str(self.created_at.month) + "/" +str(self.created_at.year)
        return self.created_at

apps/communication/forms.py
from django import forms
from django.template.context_processors import request

from .models import Messages
from apps.product.models import Comments

from django import forms
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comments.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comments
        fields = ('made_by', 'name', 'email', 'made_on', 'parent', 'content')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', "required": False}),
            'email': forms.TextInput(attrs={'class': 'form-control', "required": False}),
            'content': forms.Textarea(attrs={'class': 'form-text-control', 'placeholder':'write a comment'}),
        }

    def save(self, *args, **kwargs):
        Comments.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)


class MessageForm(forms.ModelForm):
    content = forms.CharField(label='', max_length=255, help_text='Required', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Write your messages', 'id': 'login'
                                                                                       'edit-storename'}))
    class Meta:
        model= Messages
        fields=('content',)

apps/communication/views.py
import datetime
from django import forms
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

import random
from apps.cart.cart import Cart
from apps.product.forms import AddToCartForm, AddCategoryForm, ColorSearchForm
from apps.product.models import Category, Product, ProductType, ProductSpecificationValue, Comments
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from apps.communication.forms import NewCommentForm


from apps.product.models import Product, Comments
from apps.vendor.models import Vendor
from apps.account.models import UserBase
from .forms import MessageForm
from .models import Messages





@login_required
def messages_history(request, user_or_vendor_unique_id):
    all_sender_list = []
    msg_sender_data = []
    unread_msg = Messages.objects.filter(reciever_id_unique=user_or_vendor_unique_id, is_seen=False).order_by('-created_at')
    read_msg = Messages.objects.filter(reciever_id_unique=user_or_vendor_unique_id, is_seen=True).order_by('-created_at')
    try:
        user = UserBase.objects.get(unique_id=user_or_vendor_unique_id)
    except:
        user = Vendor.objects.get(unique_id=user_or_vendor_unique_id)

    for i in unread_msg:
        vendor_messages = Messages.objects.filter(sender_id_unique=i.sender_id_unique, reciever_id_unique=user_or_vendor_unique_id,
                                                  is_seen=False)
        msg_count = vendor_messages.count()
        # this line will append that users every msg
        print(i.sender_id_unique)
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                print('place--------1')
                print(sender.is_authenticated)
                msg_sender_data.append([sender, sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, msg_count, 'a_vendor'])
            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                online = sender.created_by.is_authenticated
                print('place--------2')
                print(online)
                msg_sender_data.append([sender, sender.unique_id, sender.store_name, sender.vendor_image, i.content, i.get_date, msg_count, 'a_user'])

    for i in read_msg:
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                print('place--------3')
                print(sender.is_authenticated)
                msg_sender_data.append([sender, sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, 0, 'a_vendor'])

            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                online = sender.created_by.is_authenticated
                print('place--------4')
                print(online)
                msg_sender_data.append([sender, sender.unique_id, sender.store_name, sender.vendor_image, i.content, i.get_date, 0, 'a_user'])
    form = MessageForm()
    print(msg_sender_data)

    return render(request, 'communication/chat_platform.html', {"msg_sender_data": msg_sender_data, 'user':user, 'form': form})


@login_required
def get_message(request, user_unique_id, logged_in_user_unique_id):
    messages = Messages.objects.filter(sender_id_unique=user_unique_id, reciever_id_unique=logged_in_user_unique_id, is_seen=False)
    for status in messages:
        status.is_seen = True
        status.save()
    all_sender_list = []
    msg_sender_data = []
    unread_msg = Messages.objects.filter(reciever_id_unique=logged_in_user_unique_id, is_seen=False).order_by('-created_at')
    read_msg = Messages.objects.filter(reciever_id_unique=logged_in_user_unique_id, is_seen=True).order_by('-created_at')
    for i in unread_msg:
        vendor_messages = Messages.objects.filter(sender_id_unique=i.sender_id_unique, reciever_id_unique=logged_in_user_unique_id,
                                                  is_seen=False)
        msg_count = vendor_messages.count()
        # this line will append that users every msg
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, msg_count, 'a_vendor'])
            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender.unique_id, sender.store_name, sender.vendor_image, i.content, i.get_date, msg_count, 'a_user'])


    for i in read_msg:
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender, sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, 0, 'a_vendor'])

            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender, sender.unique_id, sender.store_name, sender.vendor_image, i.content, i.get_date, 0, 'a_user'])

    user_or_vendor_id = [user_unique_id, logged_in_user_unique_id]
    our_chat = Messages.objects.filter(sender_id_unique__in=user_or_vendor_id, reciever_id_unique__in=user_or_vendor_id).values(
        "sender_id_unique", 'content', 'created_at').order_by('-created_at')
    try:
        user_unique_id = UserBase.objects.get(unique_id=user_unique_id)
    except:
        user_unique_id = Vendor.objects.get(unique_id=user_unique_id)
    form = MessageForm()
    return render(request, 'communication/chat_platform2.html', {"our_chat":our_chat, "user_id":[user_unique_id, logged_in_user_unique_id],
                                                                "msg_sender_data": msg_sender_data, 'form': form})

@login_required
def send_message(request, user_unique_id, logged_in_user_unique_id):
    all_sender_list = []
    msg_sender_data = []

    if request.method == "POST":
        sent_message = request.POST.get('sent_message', '')
        Messages.objects.create(sender_id_unique=logged_in_user_unique_id,content=sent_message,
                                reciever_id_unique=user_unique_id)
    unread_msg = Messages.objects.filter(reciever_id_unique=logged_in_user_unique_id, is_seen=False).order_by('-created_at')
    read_msg = Messages.objects.filter(reciever_id_unique=logged_in_user_unique_id, is_seen=True).order_by('-created_at')
    for i in unread_msg:
        vendor_messages = Messages.objects.filter(sender_id_unique=i.sender_id_unique, reciever_id_unique=logged_in_user_unique_id,
                                                  is_seen=False)
        msg_count = vendor_messages.count()
        # this line will append that users every msg
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender, sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, msg_count, 'a_vendor'])
            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender, sender.unique_id, sender.store_name, sender.vendor_image, i.content, i.get_date, msg_count, 'a_user'])


    for i in read_msg:
        if i.sender_id_unique not in all_sender_list:
            all_sender_list.append(i.sender_id_unique)
            try:
                sender = UserBase.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender, sender.unique_id, sender.user_name, sender.user_image, i.content, i.get_date, 0, 'a_vendor'])
            except:
                sender = Vendor.objects.get(unique_id=i.sender_id_unique)
                msg_sender_data.append([sender, sender.unique_id, sender.store_name, sender.vendor_image, i.content, i.get_date, 0, 'a_user'])

    user_or_vendor_id = [user_unique_id, logged_in_user_unique_id]
    our_chat = Messages.objects.filter(sender_id_unique__in=user_or_vendor_id, reciever_id_unique__in=user_or_vendor_id).values(
        "sender_id_unique", 'content', 'created_at').order_by('-created_at')
    try:
        user_unique_id = UserBase.objects.get(unique_id=user_unique_id)
    except:
        user_unique_id = Vendor.objects.get(unique_id=user_unique_id)
    form = MessageForm()
    return render(request, 'communication/chat_platform2.html', {"our_chat":our_chat, "user_id":[user_unique_id, logged_in_user_unique_id],
                                                                "msg_sender_data": msg_sender_data, 'form': form})



@login_required
def send_fleet_message(request):
    if request.POST.get('do_action') == 'post_it':
        unique_id_list = request.POST.getlist('unique_id_list[]')
        sent_fleet_msg = request.POST.get('sent_fleet_msg')
        for unique_id in unique_id_list:
            Messages.objects.create(sender_id_unique=request.user.which_vendor.unique_id,
                                reciever_id_unique=unique_id, content=sent_fleet_msg)
        response = JsonResponse({})
        return response



@login_required
def get_message_ajax(request, id):
    if request.POST.get('action') == 'get_msg':
        ids = []
        user_or_vendor_id = request.POST.get('ID')
        print(user_or_vendor_id)

apps/communication/templates/communication/chat_platform2.html
{% extends 'core/base.html' %}

{% load static %}
{% block stylesheet %}{% static 'styles/communication/chat_platform.css' %}{% endblock %}
{% block stylesheet2 %}{% static 'styles/communication/chat_platform_bit1.css' %}{% endblock %}

{% block title %}{% if request.user.is_authenticated %} {{ request.user.user_name }} | {% endif %}Chat{% endblock %}

{% block content %}
<section id="main-container">
  <div class="main-box">
      <div class="main-head">
      </div>
      <div class="box">
          <div class="inside-box">
              <div class="body-row">
                  <div class="firstbox">
                      <!-- suggests that if the user a loggedin user is trying to see is a
                      a UserBase/Vendor instance then the loggedin user opposite username/storename
                      should be shown -->
                      <div class="block1">
                          <span>{% if user_id.1 == request.user.unique_id %}{{ request.user.user_name }}{% elif user_id.1 == request.user.which_vendor.unique_id  %}{{ request.user.which_vendor.store_name }} {% endif %}</span>
                          <span><i class="fa fa-pencil"></i></span>
                      </div>
                      <div class="block2">
                        {% if msg_sender_data %}
                        {% for sender in msg_sender_data %}
                        <input class="clicked-user" type="hidden" value="{{user_id.0.unique_id}}">
                        <a class="inside" data-index="{{sender.1}}" {% if sender.7 == 'a_vendor' %} href="{% url 'message_:chat_platform2' sender.1 request.user.which_vendor.unique_id %}" {% else %} href="{% url 'message_:chat_platform2' sender.1 request.user.unique_id %}" {% endif %}>
                            <div class="inner">
                                <img src="{{ sender.3.url }}" alt="profile-image">
                                <span class="active"></span>
                            </div>
                            <div class="chat-lines">
                                <div>{{sender.2}}</div>
                                <input type="hidden" value="{{sender.3}}">
                                <span class="all msg">{{sender.4 | truncatechars:25}}</span>
                                <span class="all msg1">{{sender.4 | truncatechars:20}}</span>
                                <span class="all msg2">{{sender.4 | truncatechars:15}}</span>
                                <span class="all msg3">{{sender.4 | truncatechars:10}}</span>
                            </div>
                            <span class="time">.{{sender.5}}</span>
                            {% if sender.6 != 0 %}<span class="msg_amt"> {{sender.6}}</span> {% endif %}
                        </a>
                        {% endfor %}
                        {% else %}
                          <p class="no-msg">no message</p>
                        {% endif %}
                      </div>

                  </div>
                  <div class="secondbox">
                      {% if user_id.1 == request.user.unique_id %}
                      <div class="block1">
                          <div class="inside">
                            <div class="inner">
                                <img src="{{ user_id.0.vendor_image.url }}" alt="profile-image">
                                <span class="active"></span>
                            </div>
                            <div class="chat-lines">
                                <div>{{user_id.0.store_name}}</div>
                            </div>
                          </div>
                      </div>
                      {% elif user_id.1 == request.user.which_vendor.unique_id %}
                      <div class="block1">
                          <div class="inside">
                            <div class="inner">
                                <img src="{{ user_id.0.user_image.url }}" alt="profile-image">
                                <span class="active"></span>
                            </div>
                            <div class="chat-lines">
                                <div>{{user_id.0.user_name}}</div>
                            </div>
                          </div>
                      </div>
                      {% endif %}
                      <div class="block2">
                          <div class="inside inside-b">
                              {% for msg in our_chat %}
                                  <input class="input1" type="hidden" value="{{msg.sender_id_unique}}">
                                  <!--user_id.1 contains the unique_id of the logged in user  so this
                                   checked if d current user is the same as unique_id of loggedin user-->
                                    {% if msg.sender_id_unique != user_id.1 %}
                                    <div class="float-left">
                                        <span class="chat">{{msg.content}}</span>
                                    </div>
                                    {% else %}
                                    <div class="float-right">
                                        <span class="chat">{{msg.content}}</span>
                                    </div>
                                    {% endif %}
                              {% endfor %}
                          </div>
                          <div class="msg_place">
                              <!--
                              <form method="post" action="{% if user_id.0.unique_id == request.user.which_vendor.unique_id %}{% url 'core_:send_msg' user_id.0.unique_id request.user.unique_id %}
                              {% elif user_id.0.unique_id == request.user.unique_id %}{% url 'core_:send_msg' user_id.0.unique_id request.user.which_vendor.unique_id %} {% endif %}"> -->

                              <form method="post" action="{% url 'message_:send_msg' user_id.0.unique_id user_id.1%}">
                                    {% csrf_token %}
                                  <textarea rows="5" wrap="hard soft" autofocus="autofocus" placeholder="Write a message" name="sent_message"></textarea>
                                  <button type="submit"><i class="fa fa-location-arrow"></i></button>
                              </form>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>
{% endblock %}

{% block scripts %}
    <script>
    $(document).ready(function(){
        /*$("textarea").each(function () {
          this.setAttribute("style", "height:" + (this.scrollHeight) + "px;overflow-y:hidden;");
        }).on("input", function () {
          this.style.height = "auto";
          this.style.height = (this.scrollHeight) + "px";
        });*/

        /*const tx = document.getElementsByTagName("textarea");
        for (let i = 0; i < tx.length; i++) {
          tx[i].setAttribute("style", "height:" + (tx[i].scrollHeight) + "px;overflow-y:hidden;");
          tx[i].addEventListener("input", OnInput, false);
        }
        function OnInput() {
          this.style.height = "auto";
          this.style.height = (this.scrollHeight) + "px";
        }*/

        $('form').on( 'keyup', 'textarea', function (){
            $(this).height( 0 );
            $(this).height( this.scrollHeight );
        });
        $('form').find( 'textarea' ).keyup();


        $('.msg').css('display','block')
        var unique_id = $('.secondbox > .block2 > .inside > .input1').val()
        $('.secondbox > .block1 > .inside[data-index="'+ unique_id +'"]').css('background-color','var(--lightgrey)');

        $('textarea').focus(function() {
            $(this).css("border", "1px solid var(--lightblue)") }
        )

        function windowz(){
            if (window.matchMedia("(max-width:1050px)").matches){
                var variable = $('.chat-lines > input').val()
                if (variable.length > 20) {
                    $('.all').css('display','none')
                    $('.msg1').css('display','block')
                }
            };
            if (window.matchMedia("(max-width:900px)").matches){
                var variable = $('.chat-lines > input').val()
                if (variable.length > 15) {
                    $('.all').css('display','none')
                    $('.msg2').css('display','block')
                }
            };
            if (window.matchMedia("(max-width:768px)").matches){
                var variable = $('.chat-lines > input').val()
                if (variable.length > 10) {
                    $('.all').css('display','none')
                    $('.msg3').css('display','block')
                }
            };
            if (window.matchMedia("(max-width:768px)").matches){
                var variable = $('.chat-lines > input').val()
                if (variable.length > 10) {
                    $('.all').css('display','none')
                    $('.msg2').css('display','block')
                }
            };
        }
        var y = window.matchMedia("(max-width:768px)")
        windowz()
        y.addListener(windowz)

        var clicked_user = $('.clicked-user').val()
        console.log(clicked_user)
        $('.firstbox > .block2 > .inside[data-index="' + clicked_user + '"]').css('background-color','var(--lightgrey)')
        /* $('.firstbox > .block2 > .inside').on(
            {mousedown: function(){
                $('.secondbox > .block1').children().css('background-color','var(--normalwhite)')
                $(this).css('background-color','var(--lightgrey)')
                $('.msg_amt').css('border','3px solid var(--normalwhite)')
            }}
        )*/

        $('.chatz').on(
            {click: function(e){
                e.preventDefault();
                $.ajax({
                    type:"POST",
                    data: {
                        ID: $(this).data('index'),
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        action: 'get_msg'
                    },
                    success: function(json){
                    },
                    error: function(xhr, errmsg, err){
                        console.log('completed with error');
                    }
                });

            }}
        )
    });
    </script>
{% endblock %}