NgStore2/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core_')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon/home.png'))),
    path('vendors/', include('apps.vendor.urls', namespace='vendor_')),
    path('account/', include('apps.account.urls', namespace='account_')),
    path('cart/', include('apps.cart.urls', namespace='cart_')),
    path('chat/', include('apps.chats.urls', namespace='chat_')),
    path('order/', include('apps.order.urls', namespace='order_')),
    path('checkout/', include('apps.checkout.urls', namespace='checkout_')),
    path('message/', include('apps.communication.urls', namespace='message_')),
    path('', include('apps.product.urls', namespace='product_')),
    # path('', include('apps.order.urls', namespace='order_')),
    path('__debug__/', include(debug_toolbar.urls)),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/cart/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls import url
from . import views


app_name="cart_"
urlpatterns = [
    path("cart_update_address/", views.cart_update_address, name="cart_update_address"),
    path('', views.cart_detail, name="cart_detail"),
    path('', views.shopping_cart, name="shopping_cart_"),
    path('success/', views.success, name="success_"),
    path("all/<str:rep>/", views.complete_payment, name="complete_payment2"),
]

apps/core/urls.py
from django.urls import path
from . import views
from apps import communication

app_name="core_"
urlpatterns = [
    path('', views.frontpage, name="frontpage"),
    path('contact/', views.contact, name="contact"),
    path('search/<slug:category>/', views.category_search, name="category_search"),
]

apps/product/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .templatetags import searching


app_name="product_"
urlpatterns = [
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    path('search/', views.search, name="search_"),
    path('filter/', views.filter_page, name="filter_page"),
    path('search-for', views.search_single, name="search_single"),
    path('search-brand/', views.search_brand, name="search_brand"),
    path('check-category/', views.parent_child_check, name="parent_child_check"),
    path('<slug:category_slugz>/<slug:product_slugz>/', views.product_detail, name="product_detail_"),
    path('', views.product_detail2, name="product_detail2_"),
    path('<slug:category_slug>/', views.category_list, name="category_list_"),
    path('', views.vendor_category, name="vendor_category"),
    path('add-product/', views.add_product, name="add_product_"),
    path('add-category/', views.add_category, name="add_category_"),
    path('likes_add_and_remove/<int:id>', views.likes_add_and_remove, name="likes_add_and_remove"),
    path("likes/remove_from_likes/", views.remove_from_likes, name="remove_from_likes"),
    #path('product/', views.product_entry, name="product_"),
    path('', views.make_comment, name="make_comment"),
]

apps/core/models.py
from django.db import models

# Create your models here.

apps/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import render
from django.db.models import Q
from django.contrib.auth.decorators import login_required


from apps.product.models import Product, Category
from apps.vendor.models import Vendor, Follow




def frontpage(request):
    # use line 8 > where there multiple values to b goten such as images which means we query db more than once, so we query db just once
    all_products = Product.objects.prefetch_related("product_images").filter(is_active=True, in_stock=True).order_by('-created_at')
    categories = Category.objects.filter(level=0)
    return render(request, 'core/frontpage.html', {'all_products': all_products, 'categories':categories})

def contact(request):
    return render(request, 'core/contact.html')

def category_search(request, category):
    query = category
    print(query)
    product = Product.objects.filter(Q(category__slug=query))

    #product = Product.objects.all()
    #product = Product.objects.filter(Q(category__name__icontains=query))
    brands = Product.objects.filter(is_active=True, in_stock=True)[:9]

    return render(request, 'product/search.html', {'product_search': product, 'product_search_query': query
                                                   , 'brands':brands})
"""
baby-products
computing
electronics
fashion
health-and-beauty
home-and-office
mobiles
sport
toy-and-games

Sporting
Health & Beauty
Mobiles
Fashion > women
Fashion > children > Shirts
Baby Products
Computing > Keyboard
Fashion > children
"""

apps/core/templates/core/card.html
  <a href="{% url 'product_:product_detail_' i.category.slug i.slug %}" class="">
      <div class="card">
          <div class="card-img">
              {% if i.discount_percent != 0 %}
              <span>%{{ i.discount_percent }}</span>
              {% endif %}

              {% for image in i.product_images.all %}
              {% if image.is_main %}
                  <img src="{{ image.images.url }}" alt="{{ image.images.alt_text }}">
              {% endif %}
              {% endfor %}
          </div>
          <div class="card-text">
              <strong class="title">{{ i.title|slice:":50" }}</strong>
              {% if i.discount_price != 0 %}
              <span class="money">
                  <div>
                      <strong class="discount">N{{ i.discount_price }} </strong>
                      {% if i.price_difference != 0 %}
                      <span>save N{{ i.price_difference }}</span>
                      {% endif %}
                  </div>
                  <strike class="price" style="color:#ACADA8;">N{{ i.price }} </strike>
              </span>
              {% else %}
              <strong class="price">N{{ i.price }} </strong>
              {% endif %}
          </div>
          <button data-index="{{ i.id }}" class="add-to-cart-btn" value="{{ i.id }}"><i class="fa fa-cart-plus" style="font-size:30px;"></i></button>
      </div>
  </a>
  {% block scripts %}
  <script>
        $('.add-to-cart-btn').on(
            {click: function(e){
                e.preventDefault();
                var prod_id=$(this).data('index');
                $.ajax({
                    type:"POST",
                    url:"{% url 'cart_:cart_detail' %}",
                    data: {
                        productQTY: "1",
                        productID: $(this).data('index'),
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        mainAction: 'post',
                        subAction: 'add'
                    },
                    success: function(json){
                        $("a > .cart > .qty").text(json.cart_length);
                    },
                    error: function(xhr, errmsg, err){
                        console.log('completed with error');
                    }
                });

            }}
        )
  </script>
  {% endblock %}

apps/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Contact</h1>
{% endblock %},

apps/core/templates/core/frontpage.html
{% extends 'core/base.html' %}
{% load static %}
{% load namify %}

{% block title %}Welcome{% if request.user.is_authenticated %} to {{ request.user.user_name }}{% endif %}{% endblock %}


{% block content %}
<section style="background-color:var(--normalwhite);">
    <div id="homepage">
        <div class="main-container" id="main-container">
            <!-- <div class="innerside-container">
            </div> -->
            <div class="inner-container">
                <p>NGStoreBoy</p>
                <p>where unbelievable magic lives</p>
                <ol>
                    <li><i class="fa fa-check-square"></i><span>affordable prices</span></li>
                    <li><i class="fa fa-check-square"></i><span>best servivces</span></li>
                </ol>
                
                <!-- <form method="get" action="{% url 'product_:search_' %}">
                    <div class="search-field">
                        <div class="field">
                            <div class="icon"><i class="fa fa-search"></i></div>
                            <input type="text" class="input" placeholder="Search products brands and categories" name="query">
                            <button class="is-uppercase">SEARCH</button>
                        </div>
                    </div>
                </form> -->
            </div>
        </div>
    </div>



    <div>
        <div id="category-box-inline">
            <div class="box container-fluid" id="top-selling">
                {% if all_products %}
                <div class="inner-box">
                    <div class="box-header">
                        <span class="item-1">Top Selling</span>
                    </div>
                    <div class="box-body">
                      {% for i in all_products %}
                      {% if i.is_active %}
                      {% with i as i %}
                          {% include "core/card.html" %}
                      {% endwith %}
                      {% endif %}
                      {% endfor %}
                    </div>
                </div>
                {% endif %}
            </div>

            {% if all_products %}
            <div class="box container-fluid" id="recently-viewed">
                <div class="inner-box">
                    <div class="box-header">
                        <span class="item-1">Recently Viewed</span>
                    </div>
                    <div class="box-body">
                      <div class="box-body-div">
                        {% for i in all_products|slice:":4" %}
                        <a href="{% url 'product_:product_detail_' i.category.slug i.slug %}" class="">
                          <div class="card">
                              <div class="card-img">
                                  {% for image in i.product_images.all %}
                                  {% if image.is_main %}
                                      <img src="{{ image.images.url }}" alt="{{ image.images.alt_text }}">
                                  {% endif %}
                                  {% endfor %}
                              </div>
                              <div class="card-text">
                                  <strong class="title">{{ i.title|slice:":50" }}</strong>
                              </div>
                          </div>
                        </a>
                        {% endfor %}
                      </div>
                    </div>
                </div>
            </div>
            {% endif %}

            {% if all_products %}
            <div class="box container-fluid" id="topmost">
                <div class="outside-box">
                    <div class="box-header">
                        <span class="item-1">Top Most With Early Saving</span>
                    </div>
                    <div class="box-body">
                      {% for i in all_products|slice:":4" %}
                      {% if i.is_active %}
                      {% with i as i %}
                          {% include "core/card.html" %}
                      {% endwith %}
                      {% endif %}
                      {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

apps/core/templates/core/lightbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
            <!-- Slideshow container -->
    <!-- Images used to open the lightbox -->
    <div class="row">
      <div class="column">
        <img src="img1.jpg" onclick="openModal();currentSlide(1)" class="hover-shadow">
      </div>
      <div class="column">
        <img src="img2.jpg" onclick="openModal();currentSlide(2)" class="hover-shadow">
      </div>
      <div class="column">
        <img src="img3.jpg" onclick="openModal();currentSlide(3)" class="hover-shadow">
      </div>
      <div class="column">
        <img src="img4.jpg" onclick="openModal();currentSlide(4)" class="hover-shadow">
      </div>
    </div>

    <!-- The Modal/Lightbox -->
    <div id="myModal" class="modal">
      <span class="close cursor" onclick="closeModal()">&times;</span>
      <div class="modal-content">

        <div class="mySlides">
          <div class="numbertext">1 / 4</div>
          <img src="img1_wide.jpg" style="width:100%">
        </div>

        <div class="mySlides">
          <div class="numbertext">2 / 4</div>
          <img src="img2_wide.jpg" style="width:100%">
        </div>

        <div class="mySlides">
          <div class="numbertext">3 / 4</div>
          <img src="img3_wide.jpg" style="width:100%">
        </div>

        <div class="mySlides">
          <div class="numbertext">4 / 4</div>
          <img src="img4_wide.jpg" style="width:100%">
        </div>

        <!-- Next/previous controls -->
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>

        <!-- Caption text -->
        <div class="caption-container">
          <p id="caption"></p>
        </div>

        <!-- Thumbnail image controls -->
        <div class="column">
          <img class="demo" src="img1.jpg" onclick="currentSlide(1)" alt="Nature">
        </div>

        <div class="column">
          <img class="demo" src="img2.jpg" onclick="currentSlide(2)" alt="Snow">
        </div>

        <div class="column">
          <img class="demo" src="img3.jpg" onclick="currentSlide(3)" alt="Mountains">
        </div>

        <div class="column">
          <img class="demo" src="img4.jpg" onclick="currentSlide(4)" alt="Lights">
        </div>
      </div>
    </div>
</body>
</html>
<script>
// Open the Modal
function openModal() {
  document.getElementById("myModal").style.display = "block";
}

// Close the Modal
function closeModal() {
  document.getElementById("myModal").style.display = "none";
}

var slideIndex = 1;
showSlides(slideIndex);

// Next/previous controls
function plusSlides(n) {
  showSlides(slideIndex += n);
}

// Thumbnail image controls
function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  var captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script>

apps/core/templates/core/message.html
<ul class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="{{message.tags}}"  {% endif %}>
        {{message}}
    </div>
    {% endfor %}
</ul>

apps/core/templates/core/slide.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <!-- Slideshow container -->
        <div class="slideshow-container">

          <!-- Full-width images with number and caption text -->
          <div class="mySlides fade">
            <div class="numbertext">1 / 3</div>
            <img src="img1.jpg" style="width:100%">
            <div class="text">Caption Text</div>
          </div>

          <div class="mySlides fade">
            <div class="numbertext">2 / 3</div>
            <img src="img2.jpg" style="width:100%">
            <div class="text">Caption Two</div>
          </div>

          <div class="mySlides fade">
            <div class="numbertext">3 / 3</div>
            <img src="img3.jpg" style="width:100%">
            <div class="text">Caption Three</div>
          </div>

          <!-- Next and previous buttons -->
          <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
          <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
        <br>

        <!-- The dots/circles -->
        <div style="text-align:center">
          <span class="dot" onclick="currentSlide(1)"></span>
          <span class="dot" onclick="currentSlide(2)"></span>
          <span class="dot" onclick="currentSlide(3)"></span>
        </div>
</body>
</html>
<script>
    /*ON CLICK*/
    var slideIndex = 1;
    showSlides(slideIndex);

    // Next/previous controls
    function plusSlides(n) {
      showSlides(slideIndex += n);
    }

    // Thumbnail image controls
    function currentSlide(n) {
      showSlides(slideIndex = n);
    }

    function showSlides(n) {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      var dots = document.getElementsByClassName("dot");
      if (n > slides.length) {slideIndex = 1}
      if (n < 1) {slideIndex = slides.length}
      for (i = 0; i < slides.length; i++) {
          slides[i].style.display = "none";
      }
      for (i = 0; i < dots.length; i++) {
          dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex-1].style.display = "block";
      dots[slideIndex-1].className += " active";
    }



    /*ANIMATE*/
    var slideIndex = 0;
    showSlides();

    function showSlides() {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
      }
      slideIndex++;
      if (slideIndex > slides.length) {slideIndex = 1}
      slides[slideIndex-1].style.display = "block";
      setTimeout(showSlides, 2000); // Change image every 2 seconds
    }
</script>